# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"3\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"\x85\x01\n\x0c\x43hatResponse\x12%\n\ntext_chunk\x18\x01 \x01(\x0b\x32\x0f.chat.TextChunkH\x00\x12\'\n\x0b\x61udio_chunk\x18\x02 \x01(\x0b\x32\x10.chat.AudioChunkH\x00\x12\x1a\n\x04\x64one\x18\x03 \x01(\x0b\x32\n.chat.DoneH\x00\x42\t\n\x07payload\"*\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"+\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"\x14\n\x04\x44one\x12\x0c\n\x04info\x18\x01 \x01(\t2>\n\x0b\x43hatService\x12/\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=20
  _globals['_CHATREQUEST']._serialized_end=71
  _globals['_CHATRESPONSE']._serialized_start=74
  _globals['_CHATRESPONSE']._serialized_end=207
  _globals['_TEXTCHUNK']._serialized_start=209
  _globals['_TEXTCHUNK']._serialized_end=251
  _globals['_AUDIOCHUNK']._serialized_start=253
  _globals['_AUDIOCHUNK']._serialized_end=296
  _globals['_DONE']._serialized_start=298
  _globals['_DONE']._serialized_end=318
  _globals['_CHATSERVICE']._serialized_start=320
  _globals['_CHATSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
