# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\x04\x63hat\"3\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"\x85\x01\n\x0c\x43hatResponse\x12%\n\ntext_chunk\x18\x01 \x01(\x0b\x32\x0f.chat.TextChunkH\x00\x12\'\n\x0b\x61udio_chunk\x18\x02 \x01(\x0b\x32\x10.chat.AudioChunkH\x00\x12\x1a\n\x04\x64one\x18\x03 \x01(\x0b\x32\n.chat.DoneH\x00\x42\t\n\x07payload\"*\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"+\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"\x14\n\x04\x44one\x12\x0c\n\x04info\x18\x01 \x01(\t2>\n\x0b\x43hatService\x12/\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse0\x01\x62\x06proto3'
)




_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='chat.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='chat.ChatRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='question', full_name='chat.ChatRequest.question', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=71,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='chat.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_chunk', full_name='chat.ChatResponse.text_chunk', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_chunk', full_name='chat.ChatResponse.audio_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='done', full_name='chat.ChatResponse.done', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='chat.ChatResponse.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=74,
  serialized_end=207,
)


_TEXTCHUNK = _descriptor.Descriptor(
  name='TextChunk',
  full_name='chat.TextChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='chat.TextChunk.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_last', full_name='chat.TextChunk.is_last', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=251,
)


_AUDIOCHUNK = _descriptor.Descriptor(
  name='AudioChunk',
  full_name='chat.AudioChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='chat.AudioChunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_last', full_name='chat.AudioChunk.is_last', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=296,
)


_DONE = _descriptor.Descriptor(
  name='Done',
  full_name='chat.Done',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='chat.Done.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=318,
)

_CHATRESPONSE.fields_by_name['text_chunk'].message_type = _TEXTCHUNK
_CHATRESPONSE.fields_by_name['audio_chunk'].message_type = _AUDIOCHUNK
_CHATRESPONSE.fields_by_name['done'].message_type = _DONE
_CHATRESPONSE.oneofs_by_name['payload'].fields.append(
  _CHATRESPONSE.fields_by_name['text_chunk'])
_CHATRESPONSE.fields_by_name['text_chunk'].containing_oneof = _CHATRESPONSE.oneofs_by_name['payload']
_CHATRESPONSE.oneofs_by_name['payload'].fields.append(
  _CHATRESPONSE.fields_by_name['audio_chunk'])
_CHATRESPONSE.fields_by_name['audio_chunk'].containing_oneof = _CHATRESPONSE.oneofs_by_name['payload']
_CHATRESPONSE.oneofs_by_name['payload'].fields.append(
  _CHATRESPONSE.fields_by_name['done'])
_CHATRESPONSE.fields_by_name['done'].containing_oneof = _CHATRESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
DESCRIPTOR.message_types_by_name['TextChunk'] = _TEXTCHUNK
DESCRIPTOR.message_types_by_name['AudioChunk'] = _AUDIOCHUNK
DESCRIPTOR.message_types_by_name['Done'] = _DONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)

TextChunk = _reflection.GeneratedProtocolMessageType('TextChunk', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCHUNK,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.TextChunk)
  })
_sym_db.RegisterMessage(TextChunk)

AudioChunk = _reflection.GeneratedProtocolMessageType('AudioChunk', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOCHUNK,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.AudioChunk)
  })
_sym_db.RegisterMessage(AudioChunk)

Done = _reflection.GeneratedProtocolMessageType('Done', (_message.Message,), {
  'DESCRIPTOR' : _DONE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Done)
  })
_sym_db.RegisterMessage(Done)



_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='chat.ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=320,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='chat.ChatService.Chat',
    index=0,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_CHATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
